CREATE TABLE BOOKMANAGER
(NUM NUMBER(4) CONSTRAINT BOOK_MGR_PK PRIMARY KEY,
    NAME VARCHAR2(40),
    AUTHOR VARCHAR2(40),
    PUBLISHER VARCHAR2(40),
    CATEGORY VARCHAR2(40));
    
CREATE SEQUENCE BOOK_NUM;
SELECT BOOK_NUM.CURRVAL FROM DUAL;

INSERT INTO BOOKMANAGER VALUES(BOOK_NUM.NEXTVAL, 'JAVA의 정석', '남궁성', '도우출판', '700언어');
INSERT INTO BOOKMANAGER VALUES(BOOK_NUM.NEXTVAL, '그리고 아무도 없었다', '애거사 크리스티', '해문출판사', '800문학');
INSERT INTO BOOKMANAGER VALUES(BOOK_NUM.NEXTVAL, '토비의 스프링', '이일민', '에이콘출판사', '400수학');
commit;

SELECT * FROM BOOKMANAGER;

CREATE TABLE MEMBERMANAGER
   (NUM NUMBER(4) CONSTRAINT MEMBER_MGR_PK PRIMARY KEY,
    ID_LEVEL NUMBER(4) CONSTRAINT MEMBER_LV_NN NOT NULL,
    ID VARCHAR2(40) CONSTRAINT MEMBER_ID_UK UNIQUE,
    PW VARCHAR2(40),
    NAME VARCHAR2(40),
    PHONE VARCHAR2(40),
    BIRTHDAY DATE);

INSERT INTO MEMBERMANAGER 
VALUES(
    MEMBER_NUM.NEXTVAL, 0, 'gkehdrn', 'gkehdrn', '하동구', '010-8966-9519', '1995-01-09');
commit;
    
SELECT * FROM MEMBERMANAGER;
--DROP TABLE MEMBERMANAGER;

CREATE SEQUENCE MEMBER_NUM;
    
